# Generated by Django 6.1 on 2026-08-29 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='hospitals',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='hospitals.hospital'),
        ),
    ]
